Fix Golint warning Issue
Spazzy757/paul pull request #25
Opened 2020-10-09 21:21 UTC by suramrit

## Addresses: Issue #21 

## What I have done: 
- Added small descriptions to the exported functions that were throwing the golint errors
- Did not change any function definitions or implementations 

## Could be better:
 - Can add to the exported types and function definitions to make them more descriptive

## Impact: 

Goreport for golint improved from 50% to 90%. https://goreportcard.com/report/github.com/suramrit/paul
The remaining warnings are around function definitions which I have not changed

2020-10-09 21:48 UTC, suramrit commented
hmmm.. 😕 Not really sure why the CICD test is failing for essentially not much change to the code base.  @Spazzy757 and contributors any thoughts?

2020-10-10 05:55 UTC, Spazzy757 commented
Yes this is an issue with uploading coverage report as it is running from a fork. Thank you so much for the contribution! I will finish reviewing it and if it's good I will merge it!

2020-10-10 05:57 UTC, Spazzy757 requested changes
Small typo but otherwise good to go

2020-10-10 05:57 UTC, Spazzy757 commented on pkg/github/webhooks.go
> +//IncomingWebhook handles an imcoing webhook request
Typo on incoming

2020-10-10 05:58 UTC, suramrit commented
That explains it! Thanks. 

Can you please add "hacktoberfest-accepted" label to the PR. It would count towards my hacktoberfest submissions 🙌

2020-10-10 06:02 UTC, suramrit commented on pkg/github/webhooks.go
> +//IncomingWebhook handles an imcoing webhook request
Fixed in the new push

2020-10-10 14:19 UTC, Spazzy757 approved these changes

2020-10-10 14:27 UTC, merged